name: Build And Upload

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Archive build
        run: |
          mkdir -p .temp
          tar -czf .temp/project-build.tar.gz build

      - name: Upload archive via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          source: .temp/project-build.tar.gz
          target: ~/htdocs/yariy-yaroslav.swit.vn.ua
          strip_components: 1

      - name: Extract archive
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd htdocs/yariy-yaroslav.swit.vn.ua
            tar -xzf project-build.tar.gz
            rm -rf project-build.tar.gz
            mv build/* ./
            rm -rf build